version: 1.0.{build}
image: Visual Studio 2019
build: off
test_script:
  - ps: dotnet tool restore
  - ps: dotnet format --check --dry-run --verbosity minimal
  - ps: ./cake.ps1 -target=pack

artifacts:
  - path: '3-dist\pack\**'
