version: 1.0.{build}
image: Visual Studio 2019
build: off
install:
  # https://docs.microsoft.com/zh-cn/nuget/reference/msbuild-targets#packagereadmefile
  - choco install dotnet-sdk --version 5.0.300
test_script:
  - ps: ./cake.ps1 --target=pack

artifacts:
  - path: 'dist\pack\**'
